# included templates
include:
  # 1: include the component
  - remote: "https://gitlab.com/to-be-continuous/maven/-/raw/3.9.0/templates/gitlab-ci-maven.yml"

variables:
  MAVEN_DEPLOY_ENABLED: "false"
  MAVEN_IMAGE: "vcucchie/maven:test2"
  MAVEN_CFG_DIR: "/root/.m2"

# your pipeline stages
stages:
  - debug
  - build
  - test
  - package-build
  - package-test
  - infra
  - deploy
  - acceptance
  - publish
  - infra-prod
  - production

# Define the debug job
debug:
  stage: debug
  script:
    - echo "Listing contents of Maven local repository..."
    - ls -R /root/.m2/repository/