# included templates
include:
  # 1: include the component
  - remote: "https://gitlab.com/to-be-continuous/maven/-/raw/3.9.0/templates/gitlab-ci-maven.yml"

variables:
  MAVEN_DEPLOY_ENABLED: "true"
  MAVEN_IMAGE: "vcucchie/maven:maven-3.9-alpine-cesiumwriter"
  MAVEN_CFG_DIR: "/root/.m2"
  MAVEN_SETTINGS_FILE: ${MAVEN_PROJECT_DIR}/cicd/ci-settings.xml
  MVN_FORBID_SNAPSHOT_DEPENDENCIES_DISABLED: "true"
  SONAR_HOST_URL: https://localhost:9000
  SONAR_QUALITY_GATE_ENABLED: true

# your pipeline stages
stages:
  - build
  - test
  - package-build
  - package-test
  - infra
  - deploy
  - acceptance
  - publish
  - infra-prod
  - production
