<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.orekit</groupId>
        <artifactId>oreczml-parent</artifactId>
        <version>1.1-SNAPSHOT</version>
    </parent>

    <artifactId>oreczml-tutorials</artifactId>
    <packaging>jar</packaging>

    <name>oreczml-tutorials</name>
    <url>https://gitlab.orekit.org/orekit/oreczml</url>
    <description>OreCzml core module</description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <oreczml.hipparchus.version>3.1</oreczml.hipparchus.version>
        <oreczml.maven-checkstyle-plugin.version>3.6.0</oreczml.maven-checkstyle-plugin.version>
        <!-- Checkstyle 9.3 seems to be the last version usable with JDK 8 -->
        <oreczml.checkstyle.version>9.3</oreczml.checkstyle.version>
        <oreczml.spotless.version>2.44.0</oreczml.spotless.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.orekit</groupId>
            <artifactId>orekit</artifactId>
        </dependency>
        <dependency>
            <groupId>org.orekit</groupId>
            <artifactId>oreczml-core</artifactId>
            <version>${project.parent.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.hipparchus</groupId>
            <artifactId>hipparchus-geometry</artifactId>
            <version>${oreczml.hipparchus.version}</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>${oreczml.maven-checkstyle-plugin.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>com.puppycrawl.tools</groupId>
                        <artifactId>checkstyle</artifactId>
                        <version>${oreczml.checkstyle.version}</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <configLocation>${basedir}/../checkstyle.xml</configLocation>
                    <enableRulesSummary>false</enableRulesSummary>
                    <headerLocation>${basedir}/../license-header.txt</headerLocation>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.diffplug.spotless</groupId>
                <artifactId>spotless-maven-plugin</artifactId>
                <version>${oreczml.spotless.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>apply</goal>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <java>
                        <eclipse>
                            <file>${project.basedir}/../orekit-eclipse-formatter.xml</file>
                        </eclipse>
                        <includes>
                            <include>src/main/java/**/*.java</include>
                            <include>src/test/java/**/*.java</include>
                        </includes>
                    </java>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
