<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.orekit</groupId>
        <artifactId>oreczml-parent</artifactId>
        <version>1.1-SNAPSHOT</version>
    </parent>

    <artifactId>oreczml-core</artifactId>
    <packaging>jar</packaging>

    <name>OreCzml</name>
    <url>https://gitlab.orekit.org/Zudo/oreczml</url>
    <description>OreCzml core module</description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <oreczml.czml.version>3.0.0</oreczml.czml.version>
        <oreczml.junit.jupiter.version>5.10.2</oreczml.junit.jupiter.version>
        <oreczml.mockito.version>5.5.0</oreczml.mockito.version>
        <oreczml.maven-surefire-plugin.version>3.5.0</oreczml.maven-surefire-plugin.version>
        <oreczml.maven-checkstyle-plugin.version>3.6.0</oreczml.maven-checkstyle-plugin.version>
        <!-- Checkstyle 9.3 seems to be the last version usable with JDK 8 -->
        <oreczml.checkstyle.version>9.3</oreczml.checkstyle.version>
        <oreczml.spotless.version>2.44.0</oreczml.spotless.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.orekit</groupId>
            <artifactId>orekit</artifactId>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>${oreczml.junit.jupiter.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>${oreczml.mockito.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.agi</groupId>
            <artifactId>czml-writer</artifactId>
            <version>${oreczml.czml.version}</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>${project.compiler.source}</source>
                    <target>${project.compiler.target}</target>
                    <compilerArgs>
                        <arg>-Xplugin:dataContextPlugin</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>${oreczml.maven-checkstyle-plugin.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>com.puppycrawl.tools</groupId>
                        <artifactId>checkstyle</artifactId>
                        <version>${oreczml.checkstyle.version}</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <configLocation>${basedir}/../checkstyle.xml</configLocation>
                    <enableRulesSummary>false</enableRulesSummary>
                    <headerLocation>${basedir}/../license-header.txt</headerLocation>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.diffplug.spotless</groupId>
                <artifactId>spotless-maven-plugin</artifactId>
                <version>${oreczml.spotless.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>apply</goal>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <java>
                        <eclipse>
                            <file>${project.basedir}/../orekit-eclipse-formatter.xml</file>
                        </eclipse>
                        <includes>
                            <include>src/main/java/**/*.java</include>
                            <include>src/test/java/**/*.java</include>
                        </includes>
                    </java>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
